version: '3.3'

services:
  redis:
    image: redis:latest
    networks:
      - message-net
    container_name: redis
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - message_redis:/data
    ports:
      - 6379:6379

volumes:
  message_redis:


networks:
  message-net:
    name: message-net
    driver: bridge
