services:
  api:
    container_name: message_api
    build: .
    image: message-api:v0.0.1.26.04.01
    restart: always
    depends_on:
      - redis
      - message-postgres
    ports:
      - "4040:8080"
    volumes:
      - message_instances:/message/instances
    env_file:
      - .env

  redis:
    container_name: message_redis
    image: redis:latest
    restart: always
    command: redis-server --port 6379 --appendonly yes
    volumes:
      - message_redis:/data

  message-postgres:
    container_name: message_postgres
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=message
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=message123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  message_instances:
  message_redis:
  postgres_data: