services:
  api:
    container_name: message_api
    image: message/api:local
    build: .
    restart: always
    ports:
      - 8080:8080
    volumes:
      - message_instances:/message/instances
    networks:
      - message-net
    env_file:
      - .env
    expose:
      - 8080

  frontend:
    container_name: message_frontend
    image: message/manager:local
    build: ./Message-manager-v2   
    restart: always
    ports:
      - "4040:80"
    networks:
      - message-net

volumes:
  message_instances:


networks:
  message-net:
    name: message-net
    driver: bridge
